### PR TITLE
228 - ELNA_DeAi X Handle update

### PR DESCRIPTION
**Pull request by rishikeshDpp**
made the changes to a copy of beta - all 3 constants files

we should think about storing the twitter handle in one constants file somewhere, alongside other constant variables that aren't security sensitive

no search bar changes present

### CODE REVIEW

**Comment by mohitrajane** [comment]
@rishikeshDpp storing the twitter handle as constant makes sense, can you make that change to this PR. you can store it in `src/constants/index.ts` and name it something like `ELNA_TWITTER_HANDLE`

**Comment by mohitrajane** [comment]
@rishikeshDpp please  rebase this branch with beta to fix the conflict

**Comment by rishikeshDpp** [comment]
> @rishikeshDpp please rebase this branch with beta to fix the conflict

Will do and I'll close it today

**Comment by mohitrajane** [comment]
closes #200

**Pull request merged**
